apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "nodejs"
        effect: "NoSchedule"
      
      nodeSelector:
        app: nodejs
        tier: backend
      # ----------------------------------

      containers:
      - name: nodejs
        image: node:18-alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "const http = require('http');
            const server = http.createServer((req, res) => {
              if (req.url === '/time') {
                res.writeHead(200, {'Content-Type': 'text/plain'});
                res.end(new Date().toISOString() + '\n');
              } else {
                res.writeHead(404);
                res.end('Not Found');
              }
            });
            server.listen(3000, () => console.log('Server running on 3000'));" > server.js && node server.js
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
          limits:
            cpu: "50m"
            memory: "50Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - atx.lovelydevops.xyz
    secretName: letsencrypt-prod
  rules:
  - host: atx.lovelydevops.xyz
    http:
      paths:
      - path: /time
        pathType: Prefix
        backend:
          service:
            name: nodejs-service
            port:
              number: 80